### ISSUE TITLE
Trouble with local levels in bundles

### ISSUE THREAD

**Issue by qfox** [gulp-bem/gulp-bem-bundler-fs#11]
Atm path has not returned and not resolved at all.
Need to decide in which format we should return it: relative to bundle path or absolute.

Guess relative is better since it's an attribute of a bundle, but I'm open to suggestions.

**Comment by skad0** [comment]
Is using relative path may cause any troubles or make us to do klugdes?

**Comment by qfox** [comment]
@skad0 Prob yes but I don't see how for now. Anyway we handling local paths and resolving them with bundle.path.
